version: 2
models:
  - name: stg_sales
    columns:
      - name: order_id
        tests: [not_null, unique]

  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
